# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-03 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HourEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=100)),
                ('project', models.CharField(max_length=100)),
                ('incurred_hours', models.FloatField()),
                ('incurred_money', models.FloatField()),
                ('category', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=250)),
                ('entry_type', models.CharField(max_length=100)),
                ('discipline', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('bill_rate', models.FloatField()),
                ('leave_type', models.CharField(max_length=100)),
                ('phase_name', models.CharField(max_length=100)),
                ('billable', models.BooleanField()),
                ('approved', models.BooleanField()),
            ],
        ),
    ]
