# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-03 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20170403_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourentry',
            name='month',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hourentry',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hourentry',
            name='date',
            field=models.DateField(),
        ),
    ]
