# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-03 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_auto_20170403_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('year', 'month', 'client', 'project')},
        ),
        migrations.AddField(
            model_name='invoice',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='checked_bill_rates_ok',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='invoice',
            name='checked_non_billable_ok',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='invoice',
            name='checked_phases_ok',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='invoice',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='last_checked_by',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
