# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-03 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_auto_20170403_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('checked', models.BooleanField(default=False)),
                ('checked_non_billable_ok', models.NullBooleanField()),
                ('checked_bill_rates_ok', models.NullBooleanField()),
                ('checked_phases_ok', models.NullBooleanField()),
                ('user', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='checked',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='checked_bill_rates_ok',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='checked_non_billable_ok',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='checked_phases_ok',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='last_checked_by',
        ),
        migrations.AddField(
            model_name='comments',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice'),
        ),
    ]
