# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-03 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_auto_20170403_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'get_latest_by': 'timestamp'},
        ),
    ]
