# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-03 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_auto_20170403_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='checked',
            field=models.NullBooleanField(),
        ),
    ]
