# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-03 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_auto_20170403_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourentry',
            name='client',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hourentry',
            name='notes',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='hourentry',
            name='project',
            field=models.CharField(max_length=200),
        ),
    ]
