# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-03 19:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_auto_20170403_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourentry',
            name='last_updated_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 3, 19, 52, 15, 537861, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
