# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-04 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_auto_20170403_2006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-year', '-month', 'client', 'project')},
        ),
        migrations.AddField(
            model_name='invoice',
            name='incorrect_entries_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
