# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-04 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_auto_20170404_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='has_comments',
            field=models.NullBooleanField(choices=[(None, 'Unknown'), (True, 'Yes'), (False, 'No')]),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_approved',
            field=models.NullBooleanField(choices=[(None, 'Unknown'), (True, 'Yes'), (False, 'No')]),
        ),
    ]
