# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-04 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_auto_20170404_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourentry',
            name='project_tags',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='hourentry',
            name='user_email',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
