# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-04 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_auto_20170404_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tags',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
