# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-05 14:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0017_dataupdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataupdate',
            options={'get_latest_by': 'created_at'},
        ),
        migrations.AddField(
            model_name='dataupdate',
            name='aborted',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataupdate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 4, 5, 14, 40, 1, 170140, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataupdate',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
