# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-05 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0018_auto_20170405_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourentry',
            name='calculated_is_billable',
            field=models.BooleanField(default=False),
        ),
    ]
