# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-07 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0019_hourentry_calculated_is_billable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('guid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('project_state', models.CharField(max_length=100)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('phase_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('name', models.CharField(max_length=1000)),
                ('client', models.CharField(max_length=1000)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('starts_at', models.DateField(blank=True, null=True)),
                ('ends_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='hourentry',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice'),
        ),
        migrations.AddField(
            model_name='hourentry',
            name='project_m',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.Project'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='project_m',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.Project'),
        ),
    ]
