# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-09 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0021_auto_20170409_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
