# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-09 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0022_auto_20170409_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_state',
            field=models.CharField(choices=[('C', 'Created'), ('A', 'Approved'), ('P', 'Preview'), ('S', 'Sent')], default='C', max_length=1),
        ),
    ]
