# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-09 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0024_auto_20170409_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hourentry',
            name='month',
        ),
        migrations.RemoveField(
            model_name='hourentry',
            name='year',
        ),
    ]
