# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-09 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0025_auto_20170409_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='id',
            new_name='invoice_id',
        ),
    ]
