# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-09 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0026_auto_20170409_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeetUser',
            fields=[
                ('guid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(editable=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('display_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('billable', models.BooleanField(default=False)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('invitation_pending', models.BooleanField(default=False)),
                ('billability_target', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='hourentry',
            options={'ordering': ('date', 'user_id')},
        ),
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.FeetUser'),
        ),
    ]
