# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-09 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0027_auto_20170409_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='user',
        ),
        migrations.AddField(
            model_name='hourentry',
            name='user_m',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.FeetUser'),
        ),
    ]
