# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-10 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0029_auto_20170410_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
