# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-12 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0030_auto_20170410_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourentry',
            name='calculated_has_notes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hourentry',
            name='calculated_has_phase',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hourentry',
            name='calculated_has_proper_price',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hourentry',
            name='calculated_is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_hours',
            field=models.FloatField(default=0, verbose_name='Incurred hours'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_money',
            field=models.FloatField(default=0, verbose_name='Incurred money'),
        ),
    ]
