# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-12 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import invoices.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0031_auto_20170412_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('token', models.CharField(default=invoices.models.gen_auth_token, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Project')),
            ],
        ),
    ]
