# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-20 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0032_authtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceFixedEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=300)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFixedEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_sum', models.FloatField()),
                ('description', models.CharField(max_length=300)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Project')),
            ],
        ),
        migrations.AlterField(
            model_name='hourentry',
            name='user_name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
