# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-20 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0033_auto_20170420_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectfixedentry',
            old_name='monthly_sum',
            new_name='price',
        ),
    ]
