# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-20 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0034_auto_20170420_1912'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoicefixedentry',
            unique_together=set([('invoice', 'description')]),
        ),
        migrations.AlterUniqueTogether(
            name='projectfixedentry',
            unique_together=set([('project', 'description')]),
        ),
    ]
