# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-24 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0036_hourentry_calculated_has_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='checked_no_category_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='no_category_count',
            field=models.IntegerField(default=0),
        ),
    ]
