# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-24 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0037_auto_20170424_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hourentry',
            options={'ordering': ('date', 'user_id'), 'verbose_name_plural': 'Hour entries'},
        ),
        migrations.AlterModelOptions(
            name='invoicefixedentry',
            options={'verbose_name': 'Fixed invoice entry', 'verbose_name_plural': 'Fixed invoice entries'},
        ),
        migrations.AlterModelOptions(
            name='projectfixedentry',
            options={'verbose_name': 'Fixed project entry', 'verbose_name_plural': 'Fixed project entries'},
        ),
        migrations.AlterField(
            model_name='hourentry',
            name='calculated_has_category',
            field=models.BooleanField(default=True, verbose_name='Has category'),
        ),
        migrations.AlterField(
            model_name='hourentry',
            name='calculated_has_notes',
            field=models.BooleanField(default=True, verbose_name='Has notes'),
        ),
        migrations.AlterField(
            model_name='hourentry',
            name='calculated_has_phase',
            field=models.BooleanField(default=True, verbose_name='Has phase'),
        ),
        migrations.AlterField(
            model_name='hourentry',
            name='calculated_has_proper_price',
            field=models.BooleanField(default=True, verbose_name='Has proper price'),
        ),
        migrations.AlterField(
            model_name='hourentry',
            name='calculated_is_approved',
            field=models.BooleanField(default=True, verbose_name='Is approved'),
        ),
        migrations.AlterField(
            model_name='hourentry',
            name='calculated_is_billable',
            field=models.BooleanField(default=False, verbose_name='Billable'),
        ),
    ]
