# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-08 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0039_auto_20170428_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='feetuser',
            name='slack_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hourentry',
            name='last_updated_at',
            field=models.DateTimeField(db_index=True),
        ),
    ]
