# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-08 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0040_auto_20170508_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackChannel',
            fields=[
                ('channel_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('new_project_notification', models.BooleanField(default=False)),
            ],
        ),
    ]
