# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-08 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0041_slackchannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slack_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.SlackChannel'),
        ),
    ]
