# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-12 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0042_project_slack_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonInvoiceRow',
            fields=[
                ('record_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('record_type', models.CharField(max_length=50)),
                ('billing_period_start', models.DateTimeField()),
                ('billing_period_end', models.DateTimeField()),
                ('invoice_date', models.DateTimeField()),
                ('product_code', models.CharField(max_length=255)),
                ('usage_type', models.CharField(max_length=255)),
                ('item_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('usage_start', models.DateTimeField()),
                ('usage_end', models.DateTimeField()),
                ('usage_quantity', models.FloatField()),
                ('total_cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AmazonLinkedAccount',
            fields=[
                ('linked_account_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('client', 'name')},
        ),
        migrations.AlterModelOptions(
            name='slackchannel',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='amazoninvoicerow',
            name='linked_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.AmazonLinkedAccount'),
        ),
        migrations.AddField(
            model_name='project',
            name='amazon_account',
            field=models.ManyToManyField(to='invoices.AmazonLinkedAccount'),
        ),
    ]
