# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-12 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0043_auto_20170512_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazoninvoicerow',
            name='usage_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amazoninvoicerow',
            name='usage_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
