# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-12 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0045_auto_20170512_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amazonlinkedaccount',
            options={'ordering': ('name', 'linked_account_id')},
        ),
        migrations.AlterField(
            model_name='amazoninvoicerow',
            name='invoice_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='amazon_account',
            field=models.ManyToManyField(blank=True, to='invoices.AmazonLinkedAccount'),
        ),
    ]
