# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-12 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0046_auto_20170512_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazoninvoicerow',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
            preserve_default=False,
        ),
    ]
