# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-12 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0048_feetuser_amazon_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazoninvoicerow',
            name='invoice_month',
            field=models.DateField(null=True),
        ),
    ]
