# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-13 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0050_auto_20170512_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='total_hours',
            new_name='incurred_hours',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='total_money',
            new_name='incurred_money',
        ),
    ]
