# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-13 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0051_auto_20170513_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazoninvoicerow',
            name='billing_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amazoninvoicerow',
            name='billing_period_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
