# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0053_invoice_billable_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='incurred_billable_hours',
            field=models.FloatField(default=0),
        ),
    ]
