# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0054_invoice_incurred_billable_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='admin_users',
            field=models.ManyToManyField(blank=True, to='invoices.FeetUser'),
        ),
    ]
