# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0057_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourentry',
            name='status',
            field=models.CharField(default='Unknown', max_length=30),
            preserve_default=False,
        ),
    ]
