# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0058_hourentry_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackChatMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='slackchat',
            name='members',
        ),
        migrations.AddField(
            model_name='slackchatmember',
            name='slack_chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.SlackChat'),
        ),
        migrations.AlterUniqueTogether(
            name='slackchatmember',
            unique_together=set([('slack_chat', 'member')]),
        ),
    ]
