# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0059_auto_20170522_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slackchatmember',
            old_name='member',
            new_name='member_id',
        ),
        migrations.AlterUniqueTogether(
            name='slackchatmember',
            unique_together=set([('slack_chat', 'member_id')]),
        ),
    ]
