# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0060_auto_20170522_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('invoice_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('week', models.IntegerField()),
                ('client', models.CharField(max_length=100)),
                ('project', models.CharField(max_length=100)),
                ('tags', models.CharField(blank=True, max_length=1024, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('has_comments', models.BooleanField(default=False)),
                ('incorrect_entries_count', models.IntegerField(default=0)),
                ('billable_incorrect_price_count', models.IntegerField(default=0)),
                ('non_billable_hours_count', models.IntegerField(default=0)),
                ('non_phase_specific_count', models.IntegerField(default=0)),
                ('not_approved_hours_count', models.IntegerField(default=0)),
                ('no_category_count', models.IntegerField(default=0)),
                ('empty_descriptions_count', models.IntegerField(default=0)),
                ('bill_rate_avg', models.FloatField(default=0)),
                ('incurred_hours', models.FloatField(default=0, verbose_name='Incurred hours')),
                ('incurred_billable_hours', models.FloatField(default=0)),
                ('billable_percentage', models.FloatField(default=0)),
                ('incurred_money', models.FloatField(default=0, verbose_name='Incurred money')),
                ('invoice_state', models.CharField(choices=[('C', 'Created'), ('A', 'Approved'), ('P', 'Preview'), ('S', 'Sent')], default='C', max_length=1)),
                ('project_m', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.Project')),
            ],
            options={
                'ordering': ('-year', '-month', 'client', 'project'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='weeklyreport',
            unique_together=set([('year', 'month', 'client', 'project')]),
        ),
    ]
