# Generated by Django 2.0 on 2017-12-26 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0061_slacknotificationbundle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slacknotificationbundle',
            options={'get_latest_by': 'sent_at', 'ordering': ('-sent_at', 'notification_type')},
        ),
    ]
