# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0061_auto_20171010_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklyreport',
            options={'ordering': ('-year', '-week', 'client', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='weeklyreport',
            unique_together=set([('year', 'week', 'client', 'project')]),
        ),
        migrations.RenameField(
            model_name='weeklyreport',
            old_name='invoice_id',
            new_name='weekly_report_id',
        ),
        migrations.AddField(
            model_name='hourentry',
            name='weekly_report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.WeeklyReport'),
        ),
        migrations.RemoveField(
            model_name='weeklyreport',
            name='month',
        )
    ]
