# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0062_auto_20171011_0730'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReportComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('checked', models.BooleanField(default=False)),
                ('user', models.TextField(max_length=100)),
                ('weekly_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.WeeklyReport')),
            ],
            options={
                'get_latest_by': 'timestamp',
            },
        ),
    ]
