# Generated by Django 2.0 on 2017-12-27 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex_hours', '0003_auto_20170707_0818'),
        ('invoices', '0062_auto_20171226_1057'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeetUser',
            new_name='TenkfUser',
        ),
    ]
