# Generated by Django 2.0 on 2018-01-13 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0063_auto_20171227_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authtoken',
            name='project',
        ),
        migrations.RemoveField(
            model_name='slacknotification',
            name='recipient',
        ),
        migrations.DeleteModel(
            name='AuthToken',
        ),
        migrations.DeleteModel(
            name='SlackNotification',
        ),
    ]
