# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0064_auto_20171013_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='enable_weekly_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
