# Generated by Django 2.0 on 2018-01-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0064_auto_20180113_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourentry',
            name='calculated_is_overtime',
            field=models.BooleanField(default=False, verbose_name='Is overtime'),
        ),
    ]
