# Generated by Django 2.0 on 2018-01-21 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0065_hourentry_calculated_is_overtime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenkfuser',
            options={'ordering': ('first_name', 'last_name')},
        ),
    ]
