# Generated by Django 2.0 on 2018-01-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0066_auto_20180121_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourEntryChecksum',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('sha256', models.CharField(max_length=64)),
            ],
        ),
    ]
