# Generated by Django 2.0 on 2018-02-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0069_auto_20180203_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenkfuser',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
