# Generated by Django 2.0 on 2018-02-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0071_auto_20180203_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourentry',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hourentry',
            name='approved_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hourentry',
            name='assignable_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hourentry',
            name='submitted_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
