# Generated by Django 2.0 on 2018-02-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0072_auto_20180203_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourentry',
            name='approved_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
