# Generated by Django 2.0 on 2018-02-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0073_auto_20180203_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourentry',
            name='upstream_approvable_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hourentry',
            name='upstream_approvable_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
