# Generated by Django 2.0 on 2018-02-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0075_project_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
