# Generated by Django 2.0 on 2018-02-10 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0079_auto_20180210_1358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-date', 'client', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('date', 'client', 'project')},
        ),
    ]
