# Generated by Django 2.0 on 2018-02-10 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0082_auto_20180210_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('client_m__name', 'name')},
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_m',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Client'),
        ),
    ]
