# Generated by Django 2.0 on 2018-02-10 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0083_auto_20180210_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
    ]
