# Generated by Django 2.0 on 2018-02-10 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0084_remove_project_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('date', 'project_m')},
        ),
    ]
