# Generated by Django 2.0 on 2018-02-10 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0086_auto_20180210_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='project_m',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.IntegerField(),
        ),
    ]
