# Generated by Django 2.0 on 2018-02-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0087_auto_20180210_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.IntegerField(unique=True),
        ),
    ]
