# Generated by Django 2.0 on 2018-02-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0088_auto_20180210_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hourentry',
            name='project_tags',
        ),
        migrations.AlterField(
            model_name='hourentry',
            name='upstream_id',
            field=models.IntegerField(unique=True),
        ),
    ]
