# Generated by Django 2.0 on 2018-02-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0089_auto_20180210_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazoninvoicerow',
            name='billing_period_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='amazoninvoicerow',
            name='billing_period_start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='amazoninvoicerow',
            name='invoice_month',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='amazoninvoicerow',
            name='item_description',
            field=models.CharField(max_length=1000),
        ),
    ]
