# Generated by Django 2.0 on 2018-02-10 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0091_auto_20180210_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-date',)},
        ),
    ]
