# Generated by Django 2.0 on 2018-02-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0093_remove_hourentry_project_m'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_run_sync', 'Can manually sync data'), ('can_send_notifications', 'Can manually trigger slack notifications'), ('can_see_hours_overview', 'Can see hours overview'), ('can_see_sick_leaves', 'Can see sick leaves overview'), ('can_see_flex_saldos', 'Can see flex saldos overview')),
            },
        ),
    ]
