# Generated by Django 2.0 on 2018-02-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0094_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amazonlinkedaccount',
            options={'ordering': ('name', 'linked_account_id'), 'verbose_name': 'Linked Amazon Account'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'get_latest_by': 'timestamp', 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='hourentry',
            options={'ordering': ('date', 'user_id'), 'verbose_name': 'Hour entry', 'verbose_name_plural': 'Hour entries'},
        ),
        migrations.AlterModelOptions(
            name='tenkfuser',
            options={'ordering': ('first_name', 'last_name'), 'verbose_name': '10000ft user', 'verbose_name_plural': '10000ft users'},
        ),
        migrations.AddField(
            model_name='slackchannel',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tenkfuser',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
