# Generated by Django 2.0 on 2018-02-11 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0095_auto_20180211_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='client',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='project',
        ),
    ]
