# Generated by Django 2.0 on 2018-02-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0096_auto_20180211_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenkfuser',
            name='discipline',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='tenkfuser',
            name='role',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
