# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-07 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex_hours', '0002_auto_20170707_0719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flextimecorrection',
            options={'ordering': ('date', 'user')},
        ),
        migrations.AlterModelOptions(
            name='publicholiday',
            options={'ordering': ('date',)},
        ),
        migrations.AlterModelOptions(
            name='workcontract',
            options={'ordering': ('start_date', 'user')},
        ),
        migrations.AlterField(
            model_name='flextimecorrection',
            name='adjust_by',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='flextimecorrection',
            name='set_to',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='workcontract',
            name='flex_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
